import { ReactNode, useState } from "react";
import Modal from './Modal/Modal';
import Header from './Header/Header';
import Head from 'next/head';
import styles from '../styles/Home.module.css'


interface IMainPropType{
    children?: ReactNode;
    title?: string
}

function Main({
    children,
    title = "Салон красоты"
}:IMainPropType) {

    

    return ( 
        <div className={styles.container}>
        <Head>
            <title>
                {
                    title
                }
            </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        
        {
            children
        }

        
        
        </div>
     );
}

export default Main;